workflows:
  flutter-app:
    name: Build and Release Flutter App
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_ID: "com.seuprojeto.safeplace"
        FLUTTER_BUILD_DIR: build/
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - "main"
        - "master"
        - "release/*"
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Run code generation (if needed)
        script: |
          if [ -f "pubspec.yaml" ] && grep -q build_runner pubspec.yaml; then
            flutter pub run build_runner build --delete-conflicting-outputs
          fi
      - name: Analyze project
        script: |
          flutter analyze
      - name: Run tests
        script: |
          flutter test
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign --build-dir=$FLUTTER_BUILD_DIR
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - seuemail@dominio.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: true
